# Generated by Django 6.0 on 2025-12-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_message_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
